name: pos_system
description: "A Point of Sale System with Admin and Cashier interfaces"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  fl_chart: ^0.69.2
  uuid: ^4.5.1
  barcode_widget: ^2.0.4
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqflite_common_ffi_web: ^1.0.2
  path: ^1.9.0
  file_picker: ^8.0.0
  supabase_flutter: ^2.8.0
  connectivity_plus: ^6.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  flutter_blue_plus: ^1.32.12
  esc_pos_utils_updated: ^1.1.3
  esc_pos_bluetooth_updated: ^0.5.0
  flutter_bluetooth_basic_updated: 0.1.8
  permission_handler: ^11.3.1
  http: ^1.6.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
